#!/bin/bash

# Collapse to one line (probably could just do multiline regex) and then find:
# - succeed handlers
# - attempt handlers
# - new events being kicked off
# - messages being modified (relies on the new message always being called NewMessage)

NEW_LINE='(?<=`)'
PARAMS='\([^)]*\)'
UNTIL_ARROW='.*? ->'
SUCCEED_OR_ATTEMPT="${NEW_LINE}(succeed|attempt)${PARAMS}${UNTIL_ARROW}"

TUPLE="{[^}]*}"
NEW_MESSAGE="(New)?Message = ${TUPLE},"

FROM_NEW_LINE_TO_COLON='`[^`:]*:'
UNTIL_NEW_LINE='\([^`]*'
NEW_ATTEMPT="${FROM_NEW_LINE_TO_COLON}attempt${UNTIL_NEW_LINE}"

for f in src/handlers/gerlshmud_handler_*
do
  echo -e "\n$f"
  cat $f | \
  tr -s '\r\n' '`' | \
  tr -s ' ' | \
  grep -P -o -e "($SUCCEED_OR_ATTEMPT)|(${NEW_MESSAGE})|(${NEW_ATTEMPT})" | \
  tr -d "\`"
done | tee protocol
