#!/bin/bash

# Convert logs to JSON array and feed into jq so I can just see certain fields

#cat <(echo "[") <(sed -e 's/.*/&,/' logs/gerlshmud.log) <(echo "{}]") | jq --compact-output -a '.[] | {pid, id, owner, message, event_type}'
cat <(echo "[") <(sed -e 's/.*/&,/' logs/gerlshmud.log) <(echo "{}]") | jq --compact-output -a '.[] | select(.id == "room") | {pid, id, owner, character, message, event_type, stage}'
