%% This world is used when trying out gerlshmud from the console.

%%  Create rooms on a grid named after their X,Y coordinate
%%  positions
%%
%%       Room 5,3
%%         |
%%         |
%%       Exit 5,4:s <-> 5,3:n
%%         |
%%         |
%%       Room 5,4
%%         |
%%         |
%%       Exit 5,5:s <-> 5,4:n
%%         |
%%         |
%%       Room 5,5  --- Exit 5,5:w <-> 6,5:e --- Room 6,5

-define(WORLD, [{room_5_5,
                    [{is_room, true},
                     {item, shield},
                     {item, force_field},
                     {name, <<"room">>},
                     {desc, <<"an empty space">>},
                     {icon, room},
                     {exit, exit_5_5_and_5_4},
                     ?ROOM_HANDLERS]},

                {room_5_4,
                    [{exit, exit_5_5_and_5_4},
                     {character, giant},
                     {icon, room},
                     ?ROOM_HANDLERS]},

                {room_5_3,
                    [{exit, exit_5_4_and_5_3},
                     {icon, room},
                     ?ROOM_HANDLERS]},

                {room_6_5,
                    [{exit, exit_5_5_and_6_5},
                     {icon, room},
                     ?ROOM_HANDLERS]},

                {exit_5_5_and_5_4,
                    [{{room, n}, room_5_4},
                     {{room, s}, room_5_5},
                     {icon, exit},
                     ?EXIT_HANDLERS]},

                {exit_5_4_and_5_3,
                    [{{room, n}, room_5_3},
                     {{room, s}, room_5_4},
                     {icon, exit},
                     ?EXIT_HANDLERS]},

                {exit_5_5_and_6_5,
                    [{{room, e}, room_6_5},
                     {{room, w}, room_5_5},
                     {icon, exit},
                     ?EXIT_HANDLERS]},

                {player,
                    [{name, <<"Bob">>},
                     {owner, room_5_5},
                     {room, room_5_5},
                     {hitpoints, p_hp},
                     {life, p_life},
                     {attribute, strength0},
                     {attribute, dexterity0},
                     {stamina, p_stamina},
                     {body_part, p_back},
                     {body_part, hand0},
                     {body_part, hand1},
                     {race, race0},
                     {icon, person},
                     ?CHARACTER_HANDLERS]},

                {p_hp,
                    [{hitpoints, 10},
                     {owner, player},
                     {icon, stat},
                     ?HITPOINTS_HANDLERS]},

                {p_life,
                    [{is_alive, true},
                     {owner, player},
                     {icon, stat},
                     ?LIFE_HANDLERS]},

                {force_field,
                    [{owner, player},
                     {body_parts, [back]},
                     {wielding_body_parts, [back]},
                     {name, <<"force field">>},
                     {desc, <<"MK2 quark-gluon plasma shield">>},
                     {defence_damage_modifier, 100},
                     {is_defence, true},
                     {icon, technology},
                     ?ITEM_HANDLERS]},

                {sword,
                    [{desc, <<"single-edge, one-handed sword">>},
                     {owner, player},
                     {body_parts, [hand]},
                     {wielding_body_parts, [hand]},
                     {name, <<"sword">>},
                     {attack_types, [melee]},
                     {defence_hit_modifier, 0},
                     {melee_damage_modifier, 20},
                     {is_defence, true},
                     {is_attack, true},
                     {is_auto_attack, true},
                     {resources, [{stamina, 5}]},
                     {icon, weapon},
                     ?ITEM_HANDLERS]},

                {fireball_spell,
                    [{desc, <<"fireball spell">>},
                     {owner, player},
                     {name, <<"fireball">>},
                     {effect, fireball_effect}, % I think this will get linked and become a PID
                     {attack_roll, 10},
                     {attack_action, cast},
                     {attack_types, [spell]},
                     {attack_spell_cast_base, 1},
                     {is_defence, false},
                     {is_attack, true},
                     {is_auto_attack, true},
                     {resources, [{mana, 5}]},
                     {icon, spell},
                     ?SPELL_HANDLERS]},

                {fireball_effect,
                    [{desc, <<"fireball spell">>},
                     {attack_damage, 2},
                     {attack_hit, 10},
                     {attack_effect_fire},
                     {attack_types, [spell, fire]},
                     {is_attack, false},
                     {is_defence, false}]},

                {shield,
                    [{owner, player},
                     {body_parts, [hand]},
                     {wielding_body_parts, [hand]},
                     {name, <<"shield">>},
                     {desc, <<"wood and iron bucker">>},
                     {defence_hit_modifier, 100},
                     {is_defence, true},
                     {icon, weapon},
                     ?ITEM_HANDLERS]},

                {strength0,
                    [{owner, player},
                     {type, strength},
                     {value, 17},
                     {melee_damage_modifier, 100},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {dexterity0,
                    [{owner, player},
                     {type, dexterity},
                     {value, 15},
                     {melee_hit_modifier, 100},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {p_stamina,
                    [{owner, player},
                     {type, stamina},
                     {per_tick, 1},
                     {tick_time, 10},
                     {max, 10},
                     {icon, stat},
                     ?RESOURCE_HANDLERS]},

                {p_mana,
                    [{owner, player},
                     {type, mana},
                     {per_tick, 1},
                     {tick_time, 10},
                     {max, 50},
                     % TODO change this to meter icon
                     {icon, stat},
                     ?RESOURCE_HANDLERS]},

                {hand0,
                    [{name, <<"left hand">>},
                     {owner, player},
                     {body_part, hand},
                     {max_items, 1},
                     {item, p_fist},
                     {icon, body_part},
                     ?BODY_PART_HANDLERS]},

                {hand1,
                    [{name, <<"right hand">>},
                     {owner, player},
                     {body_part, hand},
                     {max_items, 1},
                     {icon, body_part},
                     ?BODY_PART_HANDLERS]},

                {p_fist,
                    [{name, <<"left fist">>},
                     {melee_damage_modifier, 50},
                     {melee_hit_modifier, 1},
                     {owner, p_hand},
                     {character, player},
                     {wielding_body_parts, [hand]},
                     {body_part, {?PID(hand0), hand}},
                     {is_attack, true},
                     {is_auto_attack, true},
                     {resources, [{stamina, 5}]},
                     {icon, body_part},
                     ?ITEM_HANDLERS]},

                {p_back,
                    [{name, <<"back">>},
                     {owner, player},
                     {body_part, back},
                     {max_items, 2},
                     {icon, body_part},
                     ?BODY_PART_HANDLERS]},

                {race0,
                    [{owner, player},
                     {type, race},
                     {desc, <<"human">>},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {giant,
                    [{owner, room_5_4},
                     {room, room_5_4},
                     {name, <<"Pete">>},
                     {hitpoints, g_hp},
                     {life, g_life},
                     {body_part, g_hand_r},
                     {attribute, strength1},
                     {attribute, dexterity1},
                     {attribute, race1},
                     {stamina, g_stamina},
                     {icon, person},
                     ?CHARACTER_HANDLERS]},

                {g_hp,
                    [{hitpoints, 310},
                     {owner, giant},
                     {icon, stat},
                     ?HITPOINTS_HANDLERS]},

                {g_life,
                    [{is_alive, true},
                     {owner, giant},
                     {icon, stat},
                     ?LIFE_HANDLERS]},

                {g_hand_r,
                    [{name, <<"right hand">>},
                     {owner, giant},
                     {body_part, hand},
                     {item, g_club},
                     {icon, body_part},
                     ?BODY_PART_HANDLERS]},

                {strength1,
                    [{owner, giant},
                     {type, strength},
                     {value, 17},
                     {melee_damage_modifier, 50},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {dexterity1,
                    [{owner, giant},
                     {type, dexterity},
                     {value, 15},
                     {melee_hit_modifier, 50},
                     {defence_hit_modifier, 50},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {g_stamina,
                    [{owner, giant},
                     {type, stamina},
                     {per_tick, 1},
                     {tick_time, 10},
                     {max, 10},
                     {icon, stat},
                     ?RESOURCE_HANDLERS]},

                {race1,
                    [{owner, giant},
                     {type, race},
                     {defence_damage_modifier, 50},
                     {desc, <<"giant">>},
                     {icon, stat},
                     ?ATTRIBUTE_HANDLERS]},

                {g_club,
                    [{name, <<"giant club">>},
                     {melee_damage_modifier, 50},
                     {melee_hit_modifier, 5},
                     {owner, g_hand_r},
                     {character, giant},
                     {wielding_body_parts, [hand]},
                     {body_part, {?PID(g_hand_r), hand}},
                     {is_attack, true},
                     {is_auto_attack, true},
                     {resources, [{stamina, 5}]},
                     {icon, weapon},
                     ?ITEM_HANDLERS]}
                 ]).
